### ISSUE TITLE
while build csq this error show 

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq4#136]
this error occur after merge #135 d2107e2e3774ef2d95883f8daca37aa1c2015cb8 this 

In file included from csq.cpp:3:
Parser/parser.h:333:1: error: ‘CollectionUpdateNode’ does not name a type
  333 | CollectionUpdateNode parse_CollectionUpdate(TokenStream tokens){
      | ^~~~~~~~~~~~~~~~~~~~
Parser/parser.h: In function ‘NodeType StatementType(TokenStream)’:
Parser/parser.h:379:16: error: ‘COLLECTION_UPDATE’ was not declared in this scope
  379 |         type = COLLECTION_UPDATE;
      |                ^~~~~~~~~~~~~~~~~
Parser/parser.h: In function ‘std::string Compile(std::vector<std::vector<Token> >)’:
Parser/parser.h:511:18: error: ‘COLLECTION_UPDATE’ was not declared in this scope
  511 |             case COLLECTION_UPDATE:{
      |                  ^~~~~~~~~~~~~~~~~
Parser/parser.h:512:17: error: ‘CollectionUpdateNode’ was not declared in this scope
  512 |                 CollectionUpdateNode node = parse_CollectionUpdate(line);
      |                 ^~~~~~~~~~~~~~~~~~~~
Parser/parser.h:513:58: error: ‘node’ was not declared in this scope; did you mean ‘code’?
  513 |                 codeString += visit_CollectionUpdateNode(node) + "\n";
      |                                                          ^~~~
      |                                                          code
Parser/parser.h:513:31: error: ‘visit_CollectionUpdateNode’ was not declared in this scope
  513 |                 codeString += visit_CollectionUpdateNode(node) + "\n";

**Comment by WithSJ** [comment]
you not define the CollectionUpdateNode type and the COLLECTION_UPDATE constant.

**Comment by AniketKumar2500** [comment]
Yeah so I forgot to add it.
