### ISSUE TITLE
bug   memeber name is missing  isCollection 

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq4#139]
In file included from AST/visitor.h:5,
                 from csq.cpp:2:
AST/../Runtime/core.h: In function ‘void allocateVar(std::string, std::string, std::vector<Cell>)’:
AST/../Runtime/core.h:103:13: error: ‘struct Variable’ has no member named ‘isCollection’
  103 |     sym.var.isCollection = true;

**Comment by AniketKumar2500** [comment]
Its solved with my new pull request
