### ISSUE TITLE
Error while compile code 

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq4#141]
**Segmentation fault (core dumped)**

https://csqlang.github.io/documentation.html
documentation code not working maybe documentation not update but.

``` 
if 1<2:
    print("1 is small")
```

this simple code give Segmentation fault (core dumped) Error

**Comment by AniketKumar2500** [comment]
Because here tabs are not allowed to be ued as indent use simple spaces

**Comment by AniketKumar2500** [comment]
and yes due to some more changes we should have update documentation.
