### ISSUE TITLE
Seperation of concern

### ISSUE THREAD

**Issue by gekkowrld** [CsqLang/Csq4#143]
Hey just a quick question, shouldn't the .h files only contain the prototypes and necessary headers?
Then for the logic and functionality, it should be in a .c or .cpp file

**Comment by AniketKumar2500** [comment]
Yes we could use it

**Comment by AniketKumar2500** [comment]
But this separation may increase length of the codebase

**Comment by AniketKumar2500** [comment]
You are somehow right but it may create build errors

**Comment by AniketKumar2500** [comment]
In certain projects i tried to do the same thing but when compiling a source so was getting errors which suggests that header files are not able to link with their associative c/cpp file

**Comment by AniketKumar2500** [comment]
Ok so will see in that context.

**Comment by AniketKumar2500** [comment]
No because a source code in Csq is compiled down to C/C++ where for all utils certain headerfiles are there which are defined in Csq4/Builtin if script runned  globally so still it will require a Csq4 dir for every project dir.

**Comment by AniketKumar2500** [comment]
Ok

**Comment by AniketKumar2500** [comment]
Shall we close this issue then?
