### ISSUE TITLE
Code Compilation Issue with Variable Declaration

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq4#145]
When attempting to compile the provided code snippet in the CSQ language, an unexpected output is generated. The code snippet involves the declaration of variables a and b with values 1 and 2 respectively. Subsequently, the code attempts to print the value of a. However, the output displays the value of b instead. This behavior indicates a potential problem with variable declaration or handling within the CSQ language.

### Code Snippet:
```
a = 1
b = 2
print(a)

```
### Expected Output:
```
1
```
### Observed Output:
```
2.000
```

**Comment by AniketKumar2500** [comment]
First of all your code is wrong to decl a var at first we use := and for assignment we use = now see how i am evaluated and answer is right:
![Screenshot_20230822_172613](https://github.com/CsqLang/Csq4/assets/90708238/dc4e4d7b-81f5-480c-bdd3-fd1378d36269)

**Comment by AniketKumar2500** [comment]
Currently all the numbers are double but we can create our parser for int also but it will require some efforts.
