### ISSUE TITLE
Having issue when installing this language on my linux mint

### ISSUE THREAD

**Issue by usmanmusa1920** [CsqLang/Csq4#177]
Having issue when installing this programming language on my linux mint laptop.

when i run `bash build.sh` it didn't show nothing on terminal, but by the time I run:  `print 'Hello, World!'`

It print this error:  `Error: no such file "Hello, World!"`

So I don't really know whats going on, any help please? @AniketKumar2500  @WithSJ

**Comment by WithSJ** [comment]
To install CSQ, follow these steps:

    Open a terminal and navigate to the CSQ source code directory.

    Execute the following commands:


```
>>> make
>>> make install

```
Ensure that you have the include folder located in /home/user/.local because, in some cases, Linux Mint may not create this folder by default. I also encountered this issue while using Linux Mint.

Once CSQ is successfully installed, you can use the CSQ compiler as follows:



`>>> csq hello.csq`

Here's an example code in CSQ:

csq

```
a := 1
print a
print "Hello World"

```

**Comment by WithSJ** [comment]
https://csqlang.github.io/documentation.html

**Comment by usmanmusa1920** [comment]
It generate exec files like that of c++ after running the command, in need of more clarification pls

**Comment by usmanmusa1920** [comment]
Surely helped, but it takes time when ran `csq hello.csq` what's going on at that stage?

**Comment by AniketKumar2500** [comment]
The code is converted into machine code but you will find that the machine code is very much fast.

**Comment by usmanmusa1920** [comment]
Yeah alright!

**Comment by WithSJ** [comment]
I believe this issue has been resolved, so I am closing it.

**Comment by usmanmusa1920** [comment]
Please what is the full meaning of Csq?

**Comment by AniketKumar2500** [comment]
Csq is a short form whose full abbr is C square.

**Comment by WithSJ** [comment]
use discussions for general information.
