### ISSUE TITLE
Python Csq Compileing issue

### ISSUE THREAD

**Issue by WithSJ** [CsqLang/Csq4#187]
Csq code 
```
a:="Hello"
print a
```
when i compile this code in cpp Csq  Compiler it make cpp file and that file code is 

```
#include "/home/withsj/.local/include/csq/Builtin/basic.h"
int main(){

allocateVar("a", "any", s_val("Hello"));
print(id("a"));
ignore;

freeMemory();
}

```

but when i use Python Csq Compiler that time cpp file code 
```
#include "/home/withsj/Desktop/Csq4/Builtin/basic.h"
int main(int argc, char** argv){
allocateVar("a","any",
"Hello");

 return 0;
}
```
**That's why the Csq Python compiler is not compiling the code**

**Comment by AniketKumar2500** [comment]
Actually it's not compiling because I made it like that you can do certain changes to run and convert it into executable.

**Comment by AniketKumar2500** [comment]
You are right it's not producing c++ code but in csq.py try to put a print statement for final_code i could see code is translated but it's not being written into file weired.
