### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by AniketKumar2500** [CsqLang/Csq4#275]
I tried to setup Csq in my new system but got the following error:
![Screenshot_20240116_111931](https://github.com/CsqLang/Csq/assets/90708238/e18b9689-28f5-4214-8016-7872de629f27)

**Comment by AniketKumar2500** [comment]
I got a potential solution that is to use
```
sudo bash build.sh install
```

**Comment by gekkowrld** [comment]
Using `sudo` doesn't change anything, it is not a permission issue but a file issue. The solution is to create a parent folder before creating a symlink
